services:

  backend:
    build: ./backend
    container_name: backend
    volumes:
      - ./backend:/var/www
      - laravel_vendor:/var/www/vendor
    expose:
      - 9000
    networks:
      - sipantau-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www
      - ./backend/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - sipantau-network

  ml:
    build: ./ml-service
    container_name: ml-service
    volumes:
      - ./ml-service:/app
    networks:
      - sipantau-network

  frontend:
    build: ./frontend
    container_name: frontend
    restart: unless-stopped
    expose:
      - 3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
    networks:
      - sipantau-network

volumes:
  laravel_vendor:

networks:
  sipantau-network:
    external: true