name: sipantau

services:
  backend:
    build: ./backend
    container_name: backend
    restart: unless-stopped
    volumes:
      - ./backend:/var/www
      - laravel_vendor:/var/www/vendor
    expose:
      - 9000
    networks:
      - sipantau-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./backend:/var/www
      - ./backend/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
      - frontend
    networks:
      - sipantau-network

  ml:
    build:
      context: ./ml-service
      extra_hosts:
      - "files.pythonhosted.org:151.101.0.223"
    container_name: ml-service
    volumes:
      - ./ml-service:/app
    networks:
      - sipantau-network

  frontend:
    build: ./frontend
    container_name: frontend
    restart: unless-stopped
    expose:
      - 3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
    env_file:
      - ./frontend/.env.production
    networks:
      - sipantau-network

volumes:
  laravel_vendor:

networks:
  sipantau-network:
    external: true