server {
    listen 80;
    server_name sipantau.simdacloud.id;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name sipantau.simdacloud.id;

    ssl_certificate /etc/letsencrypt/live/sipantau.simdacloud.id/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/sipantau.simdacloud.id/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    
    # =========================
    # FRONTEND (Next.js)
    # =========================
    location / {
        proxy_pass http://frontend:3000;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_cache_bypass $http_upgrade;
    }

    # =========================
    # BACKEND API (Laravel)
    # =========================
    location /api {
        root /var/www/public;
        try_files $uri /index.php?$query_string;
    }

    # PHP HANDLER
    location ~ \.php$ {
        fastcgi_pass backend:9000;
        fastcgi_index index.php;

        include fastcgi_params;

        fastcgi_param SCRIPT_FILENAME /var/www/public$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;

        # IMPORTANT
        fastcgi_param HTTP_AUTHORIZATION $http_authorization;
    }
}
